name: Scheduled Jekyll Build

on:
  schedule:
    - cron: "0 16 31 12 *"  # UTC 12/31 16:00 = 台灣 01/01 00:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Jekyll
        uses: actions/jekyll-build-pages@v1

      - name: Deploy
        uses: actions/deploy-pages@v4